import type { Metadata } from 'next'
import { Plus_Jakarta_Sans } from "next/font/google"
import './globals.css'
import AnnounceBar from '@/components/AnnounceBar/AnnounceBar'
import NavBar from '@/components/NavBar/NavBar'

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Hongo',
  description: 'Generated by create next app',
  icons: "//hongotheme.myshopify.com/cdn/shop/files/favicon.png?crop=center&amp;height=32&amp;v=1683885651&amp;width=32"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={plusJakartaSans.className}>
        <AnnounceBar/>
        <NavBar/>
        {children}
        </body>
    </html>
  )
}
